<?php

namespace PEL\ParisBundle\Repository;

/**
 * ResultatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatsRepository extends \Doctrine\ORM\EntityRepository
{
}
