<?php

namespace PEL\ParisBundle\Repository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends \Doctrine\ORM\EntityRepository
{
}
